[package]
name = "d16"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.2"
itertools = "0.13.0"
miette = "7.4.0"
nom = "7.1.3"
nom_locate = "4.2.0"
pathfinding = "4.12.0"
petgraph = "0.6.5"
rand = "0.8.5"
