[package]
name = "aoc2024_01"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
itertools = "0.13.0"
rayon = "1.10.0"
strum = "0.26.3"
strum_macros = "0.26.4"
winnow = "0.6.20"


[profile.release]
opt-level = 3
